Feature: Search functionality


Scenario: VERIFY USER CAN NOT LOGIN WITH INVALID CARD- NAGATIVE

Given OPEN FB URL
Then ENTER INVlid USER AND PASSWORD
Then CLICK ON LOGIN
Then VERIFY USER SHOULD NOT LOGIN
